### PR TITLE
Update noip-renew-skd.sh

### PR DESCRIPTION
**Pull request by benyjr**
Cron scheduling script name was not correct as indicated by @Angel0ffDeath.

Was changed to:
INSTEXE=$INSTDIR/noip-renew-$USER.sh

### CODE REVIEW

**Comment by Angel0ffDeath** [comment]
@benyjr - It must be stated that by default all automatic cron configs are disabled in this version of python script. Users which want to enable them should review python script and remove all #NOCRON comments.
Otherwise your comment about shell script is correct.

**Comment by Angel0ffDeath** [comment]
> Cron scheduling script name was not correct.
> 
> Was changed to: INSTEXE=$INSTDIR/noip-renew-$USER.sh

Again forgot about me :-)

**Comment by benyjr** [comment]
OK, you got me this time.  Totally forgot to credit you on this one, @Angel0ffDeath .

**Comment by neothematrix** [comment]
again great job! I'll credit both of you as soon as I get around to update the README with some additional info!
As per the comments, I'll also add some flag to disable the cron feature on request instead of commenting it out, the reason I commented it is because I use my repo to automatically build the docker image I use.
Meanwhile, I'll merge this and un-comment the cron feature

**Pull request merged**
